name: 'Check Typing'

inputs:
  python-version:
    description: 'Python version to use'
    required: true
  uv-params:
    description: 'Params for uv'
    default: "--all-extras --dev"
  project-directory:
    description: 'Directory containing pyproject.toml (useful for monorepos)'
    default: "."

runs:
  using: composite
  steps:
      - uses: cjw296/python-action/uv-run@main
        id: uv-run
        with:
          python-version: ${{ inputs.python-version }}
          uv-params: ${{ inputs.uv-params }}
          command: "mypy src tests"
          project-directory: ${{ inputs.project-directory }}
