name: 'Run Carthorse'

inputs:
  check:
    description: 'Just check whether a tag should be created instead of creating it'
    required: false
    default: 'false'
  tag-format:
    description: 'The format to use for version tags'
    required: false
    default: 'v{version}'
  project-directory:
    description: 'Directory containing pyproject.toml (useful for monorepos)'
    default: "."

outputs:
  tag:
    description: 'The tag to create, if one should be created'
    value: ${{ steps.carthorse.outputs.tag }}

runs:
  using: composite
  steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Checkout the commit for which CI ran
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Install carthorse
        run: pip install carthorse
        shell: bash

      - name: Write .carthorse.yaml
        shell: bash
        run: |
          cd "${{ inputs.project-directory }}"
          cat > .carthorse.yaml << 'EOL'
          carthorse:
            version-from: pyproject
            tag-format: "{tag_format}"
            when:
              - version-not-tagged
            actions:
              - run: 'echo "tag=$TAG" >> "$GITHUB_OUTPUT"'
          EOL

          if [ "${{ inputs.check }}" == "false" ]; then
            echo "    - create-tag" >> .carthorse.yaml
          fi

          sed -i "s/{tag_format}/${{ inputs.tag-format }}/g" .carthorse.yaml

      - name: Show .carthorse.yaml
        shell: bash
        run: |
          cd "${{ inputs.project-directory }}"
          cat .carthorse.yaml

      - name: Run carthorse
        id: carthorse
        run: |
          cd "${{ inputs.project-directory }}"
          carthorse --config .carthorse.yaml
        shell: bash
