name: 'Run Tests'

inputs:
  python-version:
    description: 'Python version to use'
    required: true
  uv-resolution:
    description: 'Type of uv resolution to use'
    required: true
  uv-extras:
    description: 'What uv extras to install'
    default: '--all-extras'
  uv-groups:
    description: 'What uv groups to install'
    default: '--dev'

runs:
  using: composite
  steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache-dependency-glob: "**/pyproject.toml"
          cache-suffix: ${{ inputs.uv-resolution }}

      - name: Install the project
        shell: bash
        run: uv sync --all-extras --dev --resolution ${{ inputs.uv-resolution }}

      - name: Run tests
        shell: bash
        run: |
          export COVERAGE_FILE=.coverage.$GITHUB_JOB
          uv run --all-extras --dev --resolution ${{ inputs.uv-resolution }} -m pytest --cov

      - name: Upload coverage data
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data-${{ inputs.python-version }}-${{ inputs.uv-resolution }}
          path: .coverage.*
          include-hidden-files: true
          if-no-files-found: ignore
      - uses: actions/checkout@v4
