name: 'Run Tests'

inputs:
  python-version:
    description: 'Python version to use'
    required: true
  uv-params:
    description: 'Params for uv'
    default: "--all-extras --dev"
  project-directory:
    description: 'Directory containing pyproject.toml (useful for monorepos)'
    default: "."

runs:
  using: composite
  steps:
      - uses: cjw296/python-action/uv-run@main
        id: uv-run
        with:
          python-version: ${{ inputs.python-version }}
          uv-params: ${{ inputs.uv-params }}
          command: "-m pytest --cov"
          uv-command: "export COVERAGE_FILE=.coverage.__PYTHON_VERSION__-__SLUG__ && uv run"
          project-directory: ${{ inputs.project-directory }}

      - name: Upload coverage data
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data-${{ inputs.python-version }}-${{ steps.uv-run.outputs.slug }}
          path: ${{ inputs.project-directory }}/.coverage.*
          include-hidden-files: true
          if-no-files-found: ignore
