name: 'Run Tests'

inputs:
  python-version:
    description: 'Python version to use'
    required: true
  uv-params:
    description: 'Params for uv'
    default: "--all-extras --dev"

runs:
  using: composite
  steps:
      - uses: cjw296/slugify-action@v1
        id: suffix
        with:
          value: ${{ inputs.uv-params }}

      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache-dependency-glob: "**/pyproject.toml"
          cache-suffix: ${{ steps.suffix.outputs.slug }}

      - name: Run tests
        shell: bash
        run: |
          export COVERAGE_FILE=.coverage.$GITHUB_JOB
          uv run ${{ inputs.uv-params }} -m pytest --cov

      - name: Upload coverage data
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data-${{ inputs.python-version }}-${{ steps.suffix.outputs.slug }}
          path: .coverage.*
          include-hidden-files: true
          if-no-files-found: ignore
      - uses: actions/checkout@v4
