name: 'Check Code Formatting'

inputs:
  project-directory:
    description: 'Directory containing pyproject.toml (useful for monorepos)'
    default: "."

runs:
  using: composite
  steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          cache-dependency-glob: "**/pyproject.toml"

      - name: Check formatting is correct
        shell: bash
        run:  |
          cd "${{ inputs.project-directory }}"
          uv tool install ruff
          ruff format --diff 
